name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - name: Docker login
        uses: docker/login-action@v3.1.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      
      - name: Buildando imagem do Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./Dockerfile
          push: true
          tags: | 
            tags/live-bcknd:v1
            tags/live-bcknd:latest
            
